### ISSUE TITLE
Where is the *.unitypackage file?

### ISSUE THREAD

**Issue by eisenyang** [ViveSoftware/vive-registry-tool#1]

**Comment by NagaChiang** [comment]
I just found that I forgot to attach the `*.unitypackage` in the latest patch. Thanks for the reminder. Please get the package from [releases](https://github.com/ViveSoftware/vive-registry-tool/releases) or [Unity Asset Store](https://assetstore.unity.com/packages/tools/utilities/vive-registry-tool-176125).

I'll close this unless you have any further questions.
