### ISSUE TITLE
Lacks valid authentification credentials - Unity 2021.1.14f1

### ISSUE THREAD

**Issue by capmalo** [ViveSoftware/vive-registry-tool#2]
Hi !
I tried to install registery tool to get Wave SDK, but I keep getting an error after adding VIVE package registry URL :

[Package Manager Window] Cannot perform upm operation: Unable to perform online search:
Request [GET https://npm-registry.vive.com/com.htc.upm.preview.a.b.c] failed because it lacks valid authentication credentials [Unknown].

[Package Manager Window] Error searching for packages.

VIVE Registry Tool :
Registry URL Status : Added
Connection status : OK

No special network parameters, if I copy/paste registry URL in firefox i can access to the website and manually download packages.

**Comment by NagaChiang** [comment]
Hi capmalo,

Sorry for the confusion, I just take down the package with issues.

It's an unexpected behavior for Unity editor. Didn't encounter this in previous versions. Would investigate later.

I suppose the installation is successful even with the error message, right?

**Comment by NagaChiang** [comment]
I'd close the issue. Feel free to reopen if you encounter further problems.
